version: "3.3"

services:
  front-runner:
    build: .
    command: PORT=80 nodemon bin/www
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "9009:80"
    env_file:
      - .env
